Fix ANDROID_BITMAP_RESULT_SUCCESS missing in native bitmap.h
ANDROID_BITMAP_RESUT_SUCCESS spelling error in master ./frameworks/native/include/android/bitmap.h causes "make cts" compilation of cts Camera Tests to fail with the error: 'ANDROID_BITMAP_RESULT_SUCCESS' was not declared in this scope

The build fails because the cts/apps/CtsVerifier/jni/cameraanalyzer/com_android_cts_verifier_camera_analyzer_CameraTests.cpp code makes reference to ANDROID_BITMAP_RESULT_SUCCESS but bitmap.h has not defined it -- it has however defined ANDROID_BITMAP_RESUT_SUCCESS.

This patch takes the approach similar to other bitmap.h files in the code base of defining both ANDROID_BITMAP_RESULT_SUCCESS and ANDROID_BITMAP_RESUT_SUCCESS for backwards compatibility.

Change-Id: I9f1fd7b98cb9adf2f31a6cbda6642d0536cef53d
Signed-off-by: Emma Sajic <esajic@effectivelateralsolutions.co.uk>